package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"poc.eduardo-luz.eu/internal/assert"
)

func TestPing(t *testing.T) {
	rr := httptest.NewRecorder()

	req, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		// mark as failed, log the error and stop the execution of the current test
		t.Fatal(err)
	}

	//call the handler passing the ResponseRecorder and the request
	ping(rr, req)

	//call the Result of the ResponseRecorder to get the http.Response generated by the ping handler
	rs := rr.Result()

	assert.Equal(t, rs.StatusCode, http.StatusOK)

	defer rs.Body.Close()

	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}

	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")
}
